//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Voyager.MVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expedition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expedition()
        {
            this.Tickets = new HashSet<Ticket>();
            this.Drivers = new HashSet<Driver>();
            this.Hosts = new HashSet<Host>();
        }
    
        public int Id { get; set; }
        public System.DateTime EstimatedDepartureTime { get; set; }
        public System.DateTime EstimatedArrivalTime { get; set; }
        public bool HasSnackService { get; set; }
        public string DepartureLocation { get; set; }
        public string ArrivalLocation { get; set; }
        public int Distance { get; set; }
        public string RouteName { get; set; }
        public int BusId { get; set; }
        public int RouteId { get; set; }
        public int Ticket_Id { get; set; }
    
        public virtual Bus Bus { get; set; }
        public virtual Route Route { get; set; }
        public virtual Ticket Ticket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver> Drivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Host> Hosts { get; set; }
    }
}
